### ISSUE TITLE
Question: recommended CustomDumpFlags when full dump is not possible?

### ISSUE THREAD

**Issue by nbeaver** [SeanCline/PyExt#10]
I have a somewhat niche question about using PyExt: can I use `!pystack` on dump files that are not full dumps but have `CustomDumpFlags` set so that `autoInterpreterState` is still available to PyExt? (It's possible that the answer is "no, full dumps are required", which is fine, I just wanted to confirm this.)

Here is the motivation: I am troubleshooting an intermittent stack exhaustion issue (STATUS_STACK_OVERFLOW, ExceptionCode c00000fd) in a [PyQt5 program](https://github.com/paulstevensonlab/princeton-nv-center-control-program) running Python 3.6. I think it might be caused by a race condition that occurs while updating one of the PyQt widgets, but that is pure conjecture at this point. Windows Error Reporting creates the default MiniDumps that are about 18 MB in size, but when I try [enabling full dumps by setting DumpType to 2](https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) the machine locks up for many hours trying to write the dump file to disk. (I rebooted the machine after about 6 hours when it crashed overnight and it had managed to write about 330 MB to disk, but unsurprisingly WinDbg could not load the partially written dump file. If nothing else I could just let it run indefinitely to try to get a full crash dump, but the machine is unusable in this state so this is not ideal.) When I load the MiniDumps into WinDbg it warns me that "Only registers, stack and portions of memory are available" and unsurprisingly when I use PyExt on the MiniDump files I get the [expected error message that others have seen](https://github.com/SeanCline/PyExt/issues/3):

    0:000> !pystack
    Thread 0:
    ERROR: !pystack: extension exception 0x80004005.
        "ExtRemoteTyped::Field: unable to retrieve field 'tstate_head' at 70d76350"

I've made one attempt at [setting CustomDumpFlags](https://learn.microsoft.com/en-us/windows/win32/api/minidumpapiset/ne-minidumpapiset-minidump_type) to enable MiniDumpFilterMemory, MiniDumpWithProcessThreadData, MiniDumpWithThreadInfo, and MiniDumpWithCodeSegs, but that was not sufficient for PyExt and I'm not sure which flag to enable to ensure that `autoInterpreterState` is available. Is MiniDumpWithFullMemory absolutely required or will another flag suffice?

I should also mention that otherwise PyExt works splendidly on this program; when I attach WinDbg to a running process I can see the stack just fine, for example:

    0:020> .load pyext
    0:020> ~*e!pystack
    Thread 0:
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 154, in paintEvent
    		[Frame] [Globals] 
    	File "C:/Users/NV Confocal/Documents/original/gui/mainexp_gui.py", line 3085, in main
    		[Frame] [Globals] 
    	File "C:/Users/NV Confocal/Documents/original/gui/mainexp_gui.py", line 3089, in <module>
    		[Frame] [Locals] [Globals] 
    <snip>
    Thread 6:
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\socket.py", line 205, in accept
    		[Frame] [Globals] 
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\site-packages\rpyc\utils\server.py", line 140, in accept
    		[Frame] [Globals] 
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\site-packages\rpyc\utils\server.py", line 264, in start
    		[Frame] [Globals] 
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\threading.py", line 864, in run
    		[Frame] [Globals] 
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\threading.py", line 916, in _bootstrap_inner
    		[Frame] [Globals] 
    	File "C:\Users\NV Confocal\anaconda3\envs\original\lib\threading.py", line 884, in _bootstrap
    		[Frame] [Globals] 

I would be happy to pass along any of the raw dump files if they would be of any use. Let me know if any other information would be of use, this sort of debugging is not my area of expertise and I may be missing something obvious.

Version information:

- PyExt version 0.1.60 (latest, July 1)
- WinDbg client version 1.2407.24003.0
- WinDbg engine version 10.0.27668.1000
- PyQt 5.9.2
- Python 3.6.13

Related reports:

- https://github.com/SeanCline/PyExt/issues/3

**Comment by SeanCline** [comment]
Hi Nathaniel,

Unfortunately, the only way I know to reconstruct a stack trace is to create a full dump. The [automated tests](https://github.com/SeanCline/PyExt/blob/master/test/scripts/win32debug.py#L177) use `MiniDumpWithFullMemory` for this exact reason.

This is because CPython stores its bookkeeping data all over the address space. Some stuff is stored on the stack and doesn't present a huge problem, but things like the `PyThreadState` (which holds the `tstate_head`) are [on the heap](https://github.com/python/cpython/blob/v3.6.10/Python/pystate.c#L207).

No promises, but if you can get a hold of a pointer to the `PyFrameObject` at the top of the stack you're interested in, you could [pass it into !PyStack](https://github.com/SeanCline/PyExt/blob/2d68aa19c95bfd0af7ab274d82834b781f36c85b/src/pystack.cpp#L120) so it doesn't have to track down the `PyThreadState`. That will likely run into the same issue of needing heap data, so it might not even be worth the effort.

But back to the problem at hand -- slow dumps.
Setting WER's DumpType to 2 (Full dump) has always worked well for me so I wonder what's tripping it up in your situation.

Whenever I need custom rules for when to generate a dump, I set up [DebugDiag](https://www.microsoft.com/en-sg/download/details.aspx?id=103453). You can tell it to generate dumps on STATUS_STACK_OVERFLOW and hopefully it'll work better that WER.

Alternatively, you could attach WinDbg and let it break when the stack overflow happens and run `!PyStack` from there.

**Comment by nbeaver** [comment]
@SeanCline Thanks so much for the response!

**Comment by SeanCline** [comment]
@nbeaver No worries. Let me know how you make out with either DebugDiag or Windbg.

If neither works out, I could try taking a peek at one of your minidumps to see if there's any evidence on the native stack of where it is in Python code.

**Comment by nbeaver** [comment]
@SeanCline Attaching WinDbg to the process, letting it break, and running `!PyStack` from there was the ticket. Writing a full dump file is still a no-go (I'm guessing because the call stack is over 200 levels deep) but the main thing is I can see where in the code this is happening, which will go a long ways towards fixing the issue. Thanks again!
