### ISSUE TITLE
Unable to use ``!pystack`` due to error message about loading Python symbols

### ISSUE THREAD

**Issue by sonictk** [SeanCline/PyExt#2]
Hi there:

I'm trying to debug a user-mode dump using WinDbg x64 on a Python 2.7 application, but I keep getting this error when attempting to use the extension commands, even though I have `python2.7.pdb` on my `_NT_SYMBOL_PATH`. Is there anything I can do to check what symbols the extension is attempting to find?

```
Thread 0:
ERROR: !pystack: extension exception 0x80040205.
    "ExtRemoteTyped::Set: unable to evaluate 'autoInterpreterState'"
0:000> !pysymfix
Current symbol path: srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols
Adding symbol server to path...

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\symbols*https://msdl.microsoft.com/download/symbols
Deferred                                       https://driver-symbols.nvidia.com
Deferred                                       https://software.intel.com/sites/downloads/symbolssrv*http://pythonsymbols.sdcline.com/symbols
New symbol path: srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbolssrv*http://pythonsymbols.sdcline.com/symbols
Loading symbols...


*************************************************************************
***            ERROR: Python symbols could not be loaded.             ***
***   Install the debugging symbols for your version of Python##.dll  ***
***                 and add them to the symbol path.                  ***
***                                                                   ***
***   Alternatively, you run the command !pysymfix to add the Python  ***
***        symbol server created for use with this extension          ***
*************************************************************************


0:000> !pystack


*************************************************************************
***            ERROR: Python symbols could not be loaded.             ***
***   Install the debugging symbols for your version of Python##.dll  ***
***                 and add them to the symbol path.                  ***
***                                                                   ***
***   Alternatively, you run the command !pysymfix to add the Python  ***
***        symbol server created for use with this extension          ***
*************************************************************************
```

**Comment by SeanCline** [comment]
Hello!

It looks like there might be a bug in how `!pysymfix` handles semicolons. Note the missing semicolon in:
`New symbol path: srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbolssrv*http://pythonsymbols.sdcline.com/symbols`

Could you try setting your symbol path by running the command:
`.sympath srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols`

Hopefully that takes care of the problem for now. I'll have to take a look and see what `!pysymfix` could be doing wrong.

**Comment by SeanCline** [comment]
I think the latest release will fix the issue. When you get a chance, can you give it a try and let me know if `!pysymfix` works any better?

**Comment by sonictk** [comment]
Hi @SeanCline:

I will give this a go in the next few days. Sorry, work was getting a little crazy; I really appreciate you taking the time to respond to my filed ticket!

**Comment by sonictk** [comment]
Hi @SeanCline:

Sorry it took me so long to get to it, but unfortunately, it's still not working for me: 

```

0:000> .load pyext
0:000>  .sympath srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols
Symbol search path is: srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols
Expanded Symbol search path is: srv*c:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\symbols*https://msdl.microsoft.com/download/symbols
Deferred                                       https://driver-symbols.nvidia.com
Deferred                                       https://software.intel.com/sites/downloads/symbols
Deferred                                       srv*http://pythonsymbols.sdcline.com/symbols
*** WARNING: Unable to verify checksum for python27.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for python27.dll - 
0:000>  .sympath srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols
Symbol search path is: srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols
Expanded Symbol search path is: srv*c:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\symbols*https://msdl.microsoft.com/download/symbols
Deferred                                       https://driver-symbols.nvidia.com
Deferred                                       https://software.intel.com/sites/downloads/symbols
Deferred                                       srv*http://pythonsymbols.sdcline.com/symbols
*** WARNING: Unable to verify checksum for python27.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for python27.dll - 
0:000> .load pyext
0:000> !pystack


*************************************************************************
***            ERROR: Python symbols could not be loaded.             ***
***   Install the debugging symbols for your version of Python##.dll  ***
***                 and add them to the symbol path.                  ***
***                                                                   ***
***   Alternatively, you run the command !pysymfix to add the Python  ***
***        symbol server created for use with this extension          ***
*************************************************************************


Thread 0:
ERROR: !pystack: extension exception 0x80040205.
    "ExtRemoteTyped::Set: unable to evaluate 'autoInterpreterState'"
```

I'm attempting to debug a crash dump in WinDbg that was generated possibly from a Python interpreter running within a host application (Autodesk Maya), I wonder if that has anything to do with it? Would it be possible for you to provide me an example dump file where I can test if it's just something to do with my machine?

**Comment by SeanCline** [comment]
My symbol server hosts the official Python symbols. It's possible that Maya ships with a python27.dll that I don't have symbols for. Could you run the following commands? These are my go-to commands for debugging symbol issues. It should show us the python.dll checksums where windbg is looking for symbols.

```
.sym noisy
.sympath srv*C:\symbols*https://msdl.microsoft.com/download/symbols;https://driver-symbols.nvidia.com;https://software.intel.com/sites/downloads/symbols;srv*http://pythonsymbols.sdcline.com/symbols
.reload
.load pyext
lmvm python27
!checksym python27
!itoldyouso python27
!pystack
.sym quiet
```

Alternatively, if there isn't any proprietary data involved, you could capture a dump with `.dump /ma c:\location\to\dump.dmp` and email it to me so I can try to figure out what's going on.

**Comment by sonictk** [comment]
Hi @SeanCline:

Thanks for responding so quickly! Maya does ship with its own `python27.dll`, but I already have symbols for those in my `_NT_SYMBOL_PATH`. 

Unfortunately, the dump file I have is from work and contains some work-specific information; I'd have to sanitize it first before I can send it to you. It might be easier if you already have an example dump file I could use to verify that things are working on my end. I'll try using the commands listed to see if I can figure out what's going on, though.

Thanks so much!

**Comment by komrad36** [comment]
Hi @SeanCline and @sonictk,

First, Sean, thank you so much for a very useful tool!!

I wanted to mention that I was in the exact same boat as @sonictk, debugging Maya's version of Python. Like @sonictk, I have symbols for Maya's custom cut of Python27.dll, which I was adding to the symbol search path, but I was still getting the "symbols not found" error.

I built PyExt from source and did some digging and found why, so I wanted to share. The symbols not found issue occurs when debugging a *minidump*, which is what Maya generates on crash. These minidumps do not have the `autoInterpreterState` available, which is needed by PyExt to construct the stack frame (and is also the symbol PyExt checks to test for the availability of symbols).

To fix this you can manually attach a debugger and export a full dump OR a minidump-with-heap. Both options work fine. If the debugger is not attached prior to the crash you'll want to disable Maya's crash handling to ensure the program halts and you can then attach your debugger and export the dump.

To my knowledge there isn't a way to get Maya to generate minidump-with-heap on crash, is there? That would be nice.

Anyway, hope this helps!

Thanks again @SeanCline !

**Comment by SeanCline** [comment]
Holy crap, @komrad36 ! Thanks for taking the time to look into this.

I'd used the success or failure of finding an `autoInterpreterState` as a proxy for whether symbols are loaded correctly. In the typical case (live debugging, or a more detailed dump) this works well. But, as you noticed, it doesn't take into account the fact that `autoInterpreterState` might have been omitted from the dump's memory.

First, I can look into making the error message better to differentiate between symbols not being loaded and the dump file missing the `autoInterpreterState`. That doesn't help with debugging, but it can clear up some confusion.

I've done some googling around and it seems Maya only allows you to turn on and off their minidump feature, so no extra dump configuration. And that's done via the [MAYA_DEBUG_ENABLE_CRASH_REPORTING ](https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-Disable-or-Enable-Crash-Error-Reports-s.html) setting. Instead of attaching a debugger, you might have better luck with configuring [Windows Error Reporting](https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps) to create dumps with `DumpType` set to `2`.

It would be nice if PyExt could print what information _is_ available in cases where the dump is minimal but I don't know how feasible that is. Early on, `!pystack` didn't rely on the `autoInterpreterState` and instead [looked for the `_frame` local](https://github.com/SeanCline/PyExt/blob/f3ce3a1d1cfe4e2e91a8151c07c0af4435112010/pystack.cpp#L64) variable on each native stack frame. I wonder if that might be a reliable fallback for dumps which only have stack memory.

**Comment by sonictk** [comment]
@SeanCline We actually have that set up here (i.e. disabled Maya's crash handler and use WER to capture the dumps), but I don't think we've set the dump type flag appropriately. I'll give that a go and report back.

Thanks @komrad36, that's incredibly helpful information. I'll give that a go if I can catch a problem in the middle of execution in the future and I'll see about changing the way we capture WER dumps.

**Comment by komrad36** [comment]
Thank you for your quick response @SeanCline !

Oh man, it would be awesome to still be able to extract frame information from just a minidump with only stack available. That's the dream. I'll experiment locally with the commit you linked! Please let me know if I can help in other ways like testing or providing example dumps or anything.

If that doesn't work I can talk to Autodesk about the possibility of exposing an env var that lets us set the `DumpType` of the dumps created by their automated crash handler.

Good luck debugging @sonictk !

**Comment by SeanCline** [comment]
I added an error message in commit 93a431a8fedad89978a1995227f51eb3eab0e8b5 which I hope will point anyone else in the right direction when they run into this. The message looks something like:

	Thread 0:
		The dump file does not contain enough data for PyExt to work properly.
		Capture a dump with full memory to ensure PyExt can reconstruct callstacks.

I haven't had any luck constructing callstacks from minimal dumps. After some poking around, it seems like heap information is absolutely required since `PyObject`s are allocated [on the heap](https://github.com/python/cpython/blob/530f506ac91338b55cf2be71b1cdf50cb077512f/Objects/object.c#L279). Stack frame information is stored in `PyFrameObject`s so it's all on the heap.

In case you're ever curious exactly what information made it into a dump file, there's an undocumented command `.dumpdebug` which shows the minidump flags, and all of the information streams.

**Comment by sonictk** [comment]
@SeanCline @komrad36 `!pystack` works with the full dumps and heap information. You guys are fantastic; I had given up all hope on debugging these sorts of crashes. Thanks so much!

**Comment by SeanCline** [comment]
@sonictk @komrad36 Is there anything I can do to make loading the Python symbols that ship with Maya easier? If Maya ships with an official build of the Python DLL, then it should just work with [my symbol server](https://github.com/SeanCline/PythonSymbols/). Otherwise, it might be possible to make `!pysymfix` detect where to look on disk for symbols and add those paths to the sympath.

**Comment by sonictk** [comment]
@SeanCline Unfortunately I don't think Autodesk makes the Maya debug symbols publicly available (They do not actually ship _with_ Maya release). I've brought it up before, but there's no telling if that policy will change in the near future. It's a shame.

**Comment by yomon598** [comment]
I have also come across the need to debug a Python related crash from an application that ships with a Python distribution that does not make any symbols available and as a very dirty and quick hack I hardcoded the value that PyInterpreterState::makeAutoInterpreterState returns. That, along with convincing WinDbg to load symbols from a different Python build, allowed using the extension.
The native stack didn't look right, because of the different symbols, but the usefulness of being able to quickly inspect the underlying Python objects greatly outbalanced that. Maybe the stack mangling can also be somehow avoided ?
So, I think it might be useful to have an extension command to set the PyInterpreterState address from command line.

**Comment by SeanCline** [comment]
@yomon598 Thanks for the ideas. I've done a few things to try and make symbols less of a sticking point in PyExt.

First, I [fixed an issue](https://github.com/SeanCline/PythonSymbols/commit/1f92fdab094cbf5049946fb737d40b4c2fc8bb9b) in the PythonSymbols repository so `!pysymfix` should be able to automatically locate symbols for the standard versions of Python released in the last few months. If you're lucky enough that the application you're debugging uses one of those versions, then you should be good to go.

Next, I added a new extension command, `!pysetautointerpreterstate`, which can be used to manually provide the address of a PyInterpreterState. It takes an expression that evaluates to the interpreter state so, to provide an address, you do something like:

```!pysetautointerpreterstate ((_is*) 0x00000285`e7c9ecf0)```

Without using `!pysetautointerpreterstate`, `makeAutoInterpreterState()` effectively uses `!pysetautointerpreterstate _PyRuntime.gilstate.autoInterpreterState` for Python 3 and `!pysetautointerpreterstate autoInterpreterState` for Python 2.

When you get a chance, could you see if this change fits your needs? You just have to head [over here](https://ci.appveyor.com/project/SeanCline/pyext/builds/33640061) and download the artifacts of the appropriate build configuration. If it works, then I'll merge it to master and publish a new build.

I'm debating whether to document `!pysetautointerpreterstate` and write unit tests, or just leave it undocumented for power users.

In case you're curious about the rationale for using an expression rather than an address:
Different versions of Python actually use a different symbol for the `PyInterpreterState`. (Some are `_is`.) This provides a way of working around the symbol name changing in the future. Additionally, it fits with how the `makeAutoInterpreterState()` already works so it was less work.

**Comment by yomon598** [comment]
Thank you for the quick and awesome work!
Unfortunately, the application uses a customized build, so I'm currently only loading symbols from the local repository, with SYMOPT_LOAD_ANYTHING option set (if there's a better way, I do not know it).
I've tried using !pysetautointerpreterstate ((_is*) 0x00000285`e7c9ecf0) with the the correct memory address, but it doesn't seem to resolve the symbol, even though dt -t python27!_is shows it.
The exact exception text is:
"""
ERROR: !pystack: extension exception 0x80004005.
    "Unable to get type ID of 'struct _is *'"
"""
Just as a wild guess, maybe symbol options from WinDbg aren't passed over to the extension and as they don't match, they could only be resolved with SYMOPT_LOAD_ANYTHING on?
I don't have any experience with writing extensions, so that's just a guess at this point.

**Comment by SeanCline** [comment]
I just had some time to give this a try. I manually loaded a mismatched `Python38.pdb` using `.symopt+ 0x40` and used `!pysetautointerpreterstate`. It worked for me, so something must be different about our setups. (Aside from the fact that I'm using Python38. I'll give Python27 a go if I have to.)

Could you try give the expression parser a hand with something like:
`!pysetautointerpreterstate ((python27!_is*)0x285e7c9ecf0)`

**Comment by yomon598** [comment]
Sure. The build that's loaded is a variant of Stackless Python, not sure if that would matter in regards to this.
Here is the output from WinDbg:
0:012> .load pyext
0:012> ?python27+500B58
Evaluate expression: 1849887576 = 00000000`6e430b58
0:012> ?? ((python27!_is*)0x6e430b58) 
struct _is * 0x00000000`6e430b58
   +0x000 next             : 0x00000000`052aedb0 _is
   +0x008 tstate_head      : 0x00000000`052aedb0 _ts
   +0x010 modules          : 0x00000001`00000001 
   +0x018 sysdict          : 0x00000000`6e1c14a0 
   +0x020 builtins         : (null) 
   +0x028 modules_reloading : (null) 
   +0x030 codec_search_path : (null) 
   +0x038 codec_search_cache : (null) 
   +0x040 codec_error_registry : (null) 
0:012> !pysetautointerpreterstate ((python27!_is*) 0x6e430b58)
AutoInterpreterState set to: ((python27!_is*) 0x6e430b58)

0:012> !pystack
Thread 12:
ERROR: !pystack: extension exception 0x80004005.
    "Unable to get type ID of 'struct _is *'"

**Comment by SeanCline** [comment]
@yomon598 I fired up Stackless Python and, at least for Python27, PyExt works without modification. So, that's promising.

I couldn't reproduce that message, but it almost has to be coming from [this line](https://github.com/SeanCline/PyExt/blob/89dff8c91ec4f96d2ff9aecdf57c2badfaaa16bc/src/PyInterpreterState.cpp#L107). My guess is that `remoteType().GetTypeName()` was returning `struct _is *`, which isn't a symbol. Had it returned just `_is` it would have worked. I made another change and now it implicitly assumes the type from the debugging symbols. [Here's that build.](https://ci.appveyor.com/project/SeanCline/pyext/builds/33721942)

Hopefully my guesswork is accurate.

Also, it probably doesn't help you, but I just put the Stackless Python symbols into the [symbol server](https://github.com/SeanCline/PythonSymbols/tree/gh-pages).
