### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by ydder007** [SeanCline/PyExt#5]
Hi,

the current release worked fine with Python 3.9 but we recently switched to Python 3.11 and now it looks like PyExt isn't working anymore. Is there any chance to get this working with 3.11?

After calling !pystack I just get the following error in WinDbg:

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Deferred                                       srv*c:\symbols*http://pythonsymbols.sdcline.com/symbols/
Symbol search path is: srv*;srv*c:\symbols*http://pythonsymbols.sdcline.com/symbols/
Executable search path is: 
Windows 10 Version 17763 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
Edition build lab: 17763.1.amd64fre.rs5_release.180914-1434
Machine Name:
Debug session time: Thu Feb  2 01:29:45.000 2023 (UTC + 1:00)
System Uptime: 15 days 16:39:34.970
Process Uptime: 0 days 0:00:11.000
................................................................
.............
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(2288.320c): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!NtWaitForMultipleObjects+0x14:
00007ffa`5e931344 c3              ret
0:006> .load pyext
0:006> !pystack
Thread 6:
ERROR: !pystack: extension exception 0x80004002.
    "ExtRemoteTyped::Field: unable to retrieve field 'tstate_head' at 7ffa374ee200"

**Comment by SeanCline** [comment]
It looks like CPython moved `PyInterpreterState.tstate_head` into a nested struct, `PyInterpreterState.threads.head` in [this commit](https://github.com/python/cpython/commit/313f92a57bc3887026ec16adb536bb2b7580ce47#diff-cb06b7ba43789a1d6ae5bef46baa8a255b72dbcd2b44bfec7f146ea4e94dbfa0L241)

It should be doable to add an extra check [here](https://github.com/SeanCline/PyExt/blob/b67257757ef750f3bed33b47abb677f7ea1e1fe2/src/PyInterpreterState.cpp#L108) to look for the head in its new location first, but fall back on the old location for Python <3.11 support.

The extension has to do this sort of trick whenever CPython moves its internal members around. For example, [here's how it handles](https://github.com/SeanCline/PyExt/blob/b67257757ef750f3bed33b47abb677f7ea1e1fe2/src/PyInterpreterState.cpp#L46) the possible locations of the PyInterpreterState.

**Comment by SeanCline** [comment]
It turns out this is actually a bit more difficult. The `tstate_head` to `threads.head` change was easy, but CPython 3.11 also changed how stack frames work considerably. It looks like `PyFrameObject` are now [lazy-constructed](https://github.com/python/cpython/blob/f6e43e834c9712d548ce9dd2f7a1d9033e45ce51/Objects/frame_layout.md#frame-objects) and rely on on a new [`_PyInterpreterFrame`](https://github.com/python/cpython/blob/22b8d77b98a5944e688be0927b8139c49d4a7257/Include/internal/pycore_frame.h#L49) which is missing many of the members we need to construct a helpful callstack.

Looking at how the new frame data structures work, it should still be possible to generate a bare call stack, missing line numbers, I don't have a lot of free time to put into supporting the new stack frame format, but if nobody else pitches in, I'll probably get around to it someday.

**Comment by jwang-r7** [comment]
Hey, any updates on whether or not 3.11 will be supported any time soon?
